### PR TITLE
Api/teacher teacher student takes

### PR DESCRIPTION
**Pull request by StevenSavant**
Includes Updated Database Script

### CODE REVIEW

**Comment by GitWoodnj** [comment]
How many files in total did you change? I think if we merge this, it will remove all of the Redux refactor

**Comment by StevenSavant** [comment]
I only changed the API

**Comment by GitWoodnj** [comment]
If we only changed a couple of files, lets copy those files, pull master, put those files where they go, create a new branch and new PR. That will circumvent a ton of git problems

**Comment by StevenSavant** [comment]
Was there another merge on master before we started that me and Blake
didn't know about?

**Comment by GitWoodnj** [comment]
All of the redux refactor, merged this morning

**Comment by StevenSavant** [comment]
so pull, add my files, and push basically right?

**Comment by GitWoodnj** [comment]
first copy the files you changed (when you pull, they will be removed), create a new branch, put the files you copied into the new branch, push and do a PR

**Comment by StevenSavant** [comment]
Yea, I knew that part

**Pull request closed without merging**
